FROM node:18
# RUN mkdir -p ./frontend
WORKDIR /frontend
COPY ./package*.json /frontend
RUN npm install
COPY . /frontend

RUN yarn build
EXPOSE 3333

# Running the app
CMD "yarn" "dev" "--" "-p" "3333"
