version: '3.9'
services:
  frontend:
    build: 
      context: ./frontend
    container_name: proxypics__challengefrontend
    command: yarn dev
    ports:
      - '3333:3333'
    volumes:
     - ./frontend:/frontend
    depends_on:
      - backend
    environment:
      - .env
    networks:
      - front_to_back
  backend:
    container_name: proxypics_challenge_backend
    command: bundle exec rails s -b '0.0.0.0'
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    environment:
      - .env
    networks:
      - front_to_back
volumes:
  your_app_pgdata:
    external: true
networks:
  front_to_back:
    driver: bridge
  